require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const { analyzeQuery } = require('../src/services/analyzerService');
const { faker } = require('@faker-js/faker');
const prisma = new PrismaClient();

const TOTAL_QUERIES = 1000;
const DELAY_MS = 50; // 50ms between queries

// Helper to sleep
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// --- Query Generators ---
const generatePerformanceQuery = () => {
  const type = faker.helpers.arrayElement(['fast-pk', 'indexed-join', 'slow-like', 'seq-scan']);
  switch (type) {
    case 'fast-pk':
      const userId = faker.number.int({ min: 1, max: 20000 });
      return `SELECT * FROM users WHERE id = ${userId}`;
    case 'indexed-join':
      const uid = faker.number.int({ min: 1, max: 20000 });
      return `SELECT u.username, p.name, o.amount 
              FROM users u 
              JOIN orders o ON u.id = o.user_id 
              JOIN products p ON o.product_id = p.id 
              WHERE u.id = ${uid}`;
    case 'slow-like':
      const namePart = faker.person.firstName().substring(0, 3);
      return `SELECT * FROM users WHERE email LIKE '%${namePart}%'`;
    case 'seq-scan':
      const status = faker.helpers.arrayElement(['pending', 'shipped']);
      return `SELECT * FROM orders WHERE status = '${status}'`;
  }
};

const generateSyntaxErrorQuery = () => {
  const errors = [
    'SELEC * FROM users', 
    'SELECT id username FROM users', 
    'SELECT * FROM users WHRE id = 1', 
    'SELECT * FROM use', 
    'INSERT INTO users (missing_column) VALUES (1)'
  ];
  return faker.helpers.arrayElement(errors);
};

const generateLogicErrorQuery = () => {
  const flaws = [
    'SELECT * FROM users u JOIN orders o ON u.id = o.total', 
    'SELECT * FROM users u JOIN products p ON u.age = p.price', 
    'SELECT * FROM orders o JOIN users u ON o.status = u.id', 
    'SELECT * FROM products p JOIN orders o ON p.name = o.id', 
    'SELECT * FROM users WHERE 1 = 0', 
    'SELECT * FROM users WHERE age > 200'
  ];
  return faker.helpers.arrayElement(flaws);
};

// --- Main Workload ---
async function generateWorkload() {
  console.log('🚀 Starting workload generation (', TOTAL_QUERIES, 'queries)...');
  
  let generatedCounts = { Performance: 0, Syntax: 0, Logic: 0 };
  let savedCounts = { Performance: 0, Syntax: 0, Logic: 0 };
  let totalQueries = 0;

  for (let i = 0; i < TOTAL_QUERIES; i++) {
    totalQueries++;
    let sql;
    let category;
    
    // 60% Performance, 20% Syntax, 20% Logic
    const rand = Math.random();
    if (rand < 0.6) {
      sql = generatePerformanceQuery();
      category = 'Performance';
      generatedCounts.Performance++;
    } else if (rand < 0.8) {
      sql = generateSyntaxErrorQuery();
      category = 'Syntax';
      generatedCounts.Syntax++;
    } else {
      sql = generateLogicErrorQuery();
      category = 'Logic';
      generatedCounts.Logic++;
    }

    try {
      const analysis = await analyzeQuery(sql);
      
      await prisma.queryLog.create({
        data: {
          originalQuery: analysis.originalQuery,
          executionTime: analysis.executionTime,
          isSlow: analysis.isSlow || false,
          explainPlan: analysis.explainPlan,
          isSyntaxValid: analysis.isSyntaxValid,
          errorCategory: analysis.errorCategory,
          postgresError: analysis.postgresError,
          joinTypeCount: analysis.joinTypeCount,
          logicFlaws: analysis.logicFlaws.length > 0 ? analysis.logicFlaws : null
        }
      });

      if (analysis.errorCategory) {
        savedCounts[analysis.errorCategory] = (savedCounts[analysis.errorCategory] || 0) + 1;
      }
      
      // Log every 100 queries
      if ((i + 1) % 100 === 0) {
        console.log(`✅ Progress: ${i + 1}/${TOTAL_QUERIES}`);
        console.log(`   Generated: ${JSON.stringify(generatedCounts)}`);
        console.log(`   Saved:     ${JSON.stringify(savedCounts)}`);
      }
      
      await sleep(DELAY_MS);
    } catch (error) {
      console.error(`❌ Query failed (${i + 1}/${TOTAL_QUERIES}):`, error.message);
    }
  }

  console.log('\n🎉 Workload generation complete!');
  console.log('Final Stats:');
  console.log('Total generated:', totalQueries);
  console.log('Generated by category:', generatedCounts);
  console.log('Saved by category:', savedCounts);

  await prisma.$disconnect();
}

generateWorkload().catch(async (error) => {
  console.error('❌ Workload generation failed:', error);
  await prisma.$disconnect();
  process.exit(1);
});
